//! PLY (Polygon File Format) support
//!
//! This module provides functionality to import and export PLY files.

use crate::geometry::Point;
use crate::mesh::mesh_data::{Mesh3D, MeshVertex};
use std::fs::File;
use std::io::{BufRead, BufReader, Read, Write};

/// PLY file format writer
pub struct PlyWriter {
    file: File,
    binary: bool,
}

impl PlyWriter {
    /// Create a new PLY writer
    pub fn new(file_path: &str, binary: bool) -> Result<Self, std::io::Error> {
        let file = File::create(file_path)?;
        Ok(Self { file, binary })
    }

    /// Write mesh to PLY file
    pub fn write_mesh(&mut self, mesh: &Mesh3D) -> Result<(), std::io::Error> {
        // Write header
        self.write_header(mesh)?;

        // Write vertices
        self.write_vertices(mesh)?;

        // Write faces
        self.write_faces(mesh)?;

        Ok(())
    }

    /// Write PLY header
    fn write_header(&mut self, mesh: &Mesh3D) -> Result<(), std::io::Error> {
        writeln!(self.file, "ply")?;
        writeln!(
            self.file,
            "format {}",
            if self.binary {
                "binary_little_endian 1.0"
            } else {
                "ascii 1.0"
            }
        )?;
        writeln!(self.file, "comment Generated by BrepRs")?;
        writeln!(self.file, "element vertex {}", mesh.vertices.len())?;
        writeln!(self.file, "property float x")?;
        writeln!(self.file, "property float y")?;
        writeln!(self.file, "property float z")?;

        // Add normal properties if available
        if mesh.vertices.iter().any(|v| v.normal.is_some()) {
            writeln!(self.file, "property float nx")?;
            writeln!(self.file, "property float ny")?;
            writeln!(self.file, "property float nz")?;
        }

        // Add color properties if available
        if mesh.vertices.iter().any(|v| v.color.is_some()) {
            writeln!(self.file, "property uchar red")?;
            writeln!(self.file, "property uchar green")?;
            writeln!(self.file, "property uchar blue")?;
            writeln!(self.file, "property uchar alpha")?;
        }

        // Count faces
        let face_count = mesh.faces.len()
            + mesh.tetrahedrons.len() * 4
            + mesh.hexahedrons.len() * 6
            + mesh.prisms.len() * 5;
        writeln!(self.file, "element face {}", face_count)?;
        writeln!(self.file, "property list uchar int vertex_indices")?;
        writeln!(self.file, "end_header")?;

        Ok(())
    }

    /// Write vertices
    fn write_vertices(&mut self, mesh: &Mesh3D) -> Result<(), std::io::Error> {
        for vertex in &mesh.vertices {
            if self.binary {
                // Write binary format
                let x = vertex.point.x as f32;
                let y = vertex.point.y as f32;
                let z = vertex.point.z as f32;
                self.file.write_all(&x.to_le_bytes())?;
                self.file.write_all(&y.to_le_bytes())?;
                self.file.write_all(&z.to_le_bytes())?;

                // Write normal if available
                if let Some(normal) = vertex.normal {
                    let nx = normal[0] as f32;
                    let ny = normal[1] as f32;
                    let nz = normal[2] as f32;
                    self.file.write_all(&nx.to_le_bytes())?;
                    self.file.write_all(&ny.to_le_bytes())?;
                    self.file.write_all(&nz.to_le_bytes())?;
                }

                // Write color if available
                if let Some(color) = vertex.color {
                    let r = (color[0] * 255.0) as u8;
                    let g = (color[1] * 255.0) as u8;
                    let b = (color[2] * 255.0) as u8;
                    let a = (color[3] * 255.0) as u8;
                    self.file.write_all(&[r, g, b, a])?;
                }
            } else {
                write!(
                    self.file,
                    "{} {} {}",
                    vertex.point.x, vertex.point.y, vertex.point.z
                )?;

                // Write normal if available
                if let Some(normal) = vertex.normal {
                    write!(self.file, " {} {} {}", normal[0], normal[1], normal[2])?;
                }

                // Write color if available
                if let Some(color) = vertex.color {
                    let r = (color[0] * 255.0) as u8;
                    let g = (color[1] * 255.0) as u8;
                    let b = (color[2] * 255.0) as u8;
                    let a = (color[3] * 255.0) as u8;
                    write!(self.file, " {} {} {} {}", r, g, b, a)?;
                }
                writeln!(self.file)?;
            }
        }

        Ok(())
    }

    /// Write faces
    fn write_faces(&mut self, mesh: &Mesh3D) -> Result<(), std::io::Error> {
        // Write regular faces
        for face in &mesh.faces {
            if self.binary {
                // Write binary format
                let count = face.vertices.len() as u8;
                self.file.write_all(&[count])?;
                for &v in &face.vertices {
                    let vertex_index = v as i32;
                    self.file.write_all(&vertex_index.to_le_bytes())?;
                }
            } else {
                write!(self.file, "{}", face.vertices.len())?;
                for &v in &face.vertices {
                    write!(self.file, " {}", v)?;
                }
                writeln!(self.file)?;
            }
        }

        // Write tetrahedron faces
        for tetra in &mesh.tetrahedrons {
            let vertices = [tetra.vertices[0], tetra.vertices[1], tetra.vertices[2]];
            if self.binary {
                self.file.write_all(&[3])?;
                for &v in &vertices {
                    let vertex_index = v as i32;
                    self.file.write_all(&vertex_index.to_le_bytes())?;
                }
            } else {
                write!(
                    self.file,
                    "3 {} {} {}",
                    vertices[0], vertices[1], vertices[2]
                )?;
                writeln!(self.file)?;
            }

            let vertices = [tetra.vertices[0], tetra.vertices[2], tetra.vertices[3]];
            if self.binary {
                self.file.write_all(&[3])?;
                for &v in &vertices {
                    let vertex_index = v as i32;
                    self.file.write_all(&vertex_index.to_le_bytes())?;
                }
            } else {
                write!(
                    self.file,
                    "3 {} {} {}",
                    vertices[0], vertices[1], vertices[2]
                )?;
                writeln!(self.file)?;
            }

            let vertices = [tetra.vertices[0], tetra.vertices[3], tetra.vertices[1]];
            if self.binary {
                self.file.write_all(&[3])?;
                for &v in &vertices {
                    let vertex_index = v as i32;
                    self.file.write_all(&vertex_index.to_le_bytes())?;
                }
            } else {
                write!(
                    self.file,
                    "3 {} {} {}",
                    vertices[0], vertices[1], vertices[2]
                )?;
                writeln!(self.file)?;
            }

            let vertices = [tetra.vertices[1], tetra.vertices[3], tetra.vertices[2]];
            if self.binary {
                self.file.write_all(&[3])?;
                for &v in &vertices {
                    let vertex_index = v as i32;
                    self.file.write_all(&vertex_index.to_le_bytes())?;
                }
            } else {
                write!(
                    self.file,
                    "3 {} {} {}",
                    vertices[0], vertices[1], vertices[2]
                )?;
                writeln!(self.file)?;
            }
        }

        // Write hexahedron faces (simplified)
        for hex in &mesh.hexahedrons {
            // Write each face of the hexahedron
            let faces = [
                [
                    hex.vertices[0],
                    hex.vertices[1],
                    hex.vertices[2],
                    hex.vertices[3],
                ],
                [
                    hex.vertices[4],
                    hex.vertices[5],
                    hex.vertices[6],
                    hex.vertices[7],
                ],
                [
                    hex.vertices[0],
                    hex.vertices[1],
                    hex.vertices[5],
                    hex.vertices[4],
                ],
                [
                    hex.vertices[1],
                    hex.vertices[2],
                    hex.vertices[6],
                    hex.vertices[5],
                ],
                [
                    hex.vertices[2],
                    hex.vertices[3],
                    hex.vertices[7],
                    hex.vertices[6],
                ],
                [
                    hex.vertices[3],
                    hex.vertices[0],
                    hex.vertices[4],
                    hex.vertices[7],
                ],
            ];

            for face in &faces {
                if self.binary {
                    self.file.write_all(&[4])?;
                    for &v in face {
                        let vertex_index = v as i32;
                        self.file.write_all(&vertex_index.to_le_bytes())?;
                    }
                } else {
                    write!(self.file, "4")?;
                    for &v in face {
                        write!(self.file, " {}", v)?;
                    }
                    writeln!(self.file)?;
                }
            }
        }

        // Write prism faces (simplified)
        for prism in &mesh.prisms {
            // Write triangular faces
            let tri_faces: [[usize; 3]; 3] = [
                [prism.vertices[0], prism.vertices[1], prism.vertices[2]],
                [prism.vertices[3], prism.vertices[4], prism.vertices[5]],
                [prism.vertices[0], prism.vertices[1], prism.vertices[4]],
            ];

            // Write quad faces
            let quad_faces: [[usize; 4]; 2] = [
                [
                    prism.vertices[1],
                    prism.vertices[2],
                    prism.vertices[5],
                    prism.vertices[4],
                ],
                [
                    prism.vertices[2],
                    prism.vertices[0],
                    prism.vertices[3],
                    prism.vertices[5],
                ],
            ];

            for face in tri_faces.iter() {
                if self.binary {
                    self.file.write_all(&[3])?;
                    for &v in face {
                        let vertex_index = v as i32;
                        self.file.write_all(&vertex_index.to_le_bytes())?;
                    }
                } else {
                    write!(self.file, "3")?;
                    for &v in face {
                        write!(self.file, " {}", v)?;
                    }
                    writeln!(self.file)?;
                }
            }

            for face in quad_faces.iter() {
                if self.binary {
                    self.file.write_all(&[4])?;
                    for &v in face {
                        let vertex_index = v as i32;
                        self.file.write_all(&vertex_index.to_le_bytes())?;
                    }
                } else {
                    write!(self.file, "4")?;
                    for &v in face {
                        write!(self.file, " {}", v)?;
                    }
                    writeln!(self.file)?;
                }
            }
        }

        Ok(())
    }
}

/// PLY header information
pub struct PlyHeaderInfo {
    pub vertex_count: usize,
    pub face_count: usize,
    pub has_normals: bool,
    pub has_colors: bool,
}

/// PLY file format reader
#[allow(dead_code)]
pub struct PlyReader {
    reader: BufReader<File>,
    binary: bool,
}

impl PlyReader {
    /// Create a new PLY reader
    pub fn new(file_path: &str) -> Result<Self, std::io::Error> {
        let file = File::open(file_path)?;
        let mut reader = BufReader::new(file);

        // Read header to determine format
        let mut line = String::new();
        reader.read_line(&mut line)?;
        if !line.trim().eq("ply") {
            return Err(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                "Not a valid PLY file",
            ));
        }

        let mut binary = false;
        loop {
            line.clear();
            let bytes_read = reader.read_line(&mut line)?;
            if bytes_read == 0 {
                break;
            }

            let trimmed = line.trim();
            if trimmed.starts_with("format") {
                if trimmed.contains("binary") {
                    binary = true;
                }
            } else if trimmed.eq("end_header") {
                break;
            }
        }

        Ok(Self { reader, binary })
    }

    /// Read mesh from PLY file
    pub fn read_mesh(&mut self) -> Result<Mesh3D, std::io::Error> {
        let mut mesh = Mesh3D::new();

        // Read header information
        let header_info = self.read_header()?;

        // Read vertices
        self.read_vertices(&mut mesh, &header_info)?;

        // Read faces
        self.read_faces(&mut mesh, &header_info)?;

        Ok(mesh)
    }

    /// Read header information
    fn read_header(&mut self) -> Result<PlyHeaderInfo, std::io::Error> {
        let mut vertex_count = 0;
        let mut face_count = 0;
        let mut has_normals = false;
        let mut has_colors = false;

        let mut line = String::new();
        loop {
            line.clear();
            let bytes_read = self.reader.read_line(&mut line)?;
            if bytes_read == 0 {
                break;
            }

            let trimmed = line.trim();
            if trimmed.starts_with("element vertex") {
                if let Some(count_str) = trimmed.split_whitespace().nth(2) {
                    vertex_count = count_str.parse().map_err(|_| {
                        std::io::Error::new(
                            std::io::ErrorKind::InvalidData,
                            "Invalid vertex count in PLY header",
                        )
                    })?;
                }
            } else if trimmed.starts_with("element face") {
                if let Some(count_str) = trimmed.split_whitespace().nth(2) {
                    face_count = count_str.parse().map_err(|_| {
                        std::io::Error::new(
                            std::io::ErrorKind::InvalidData,
                            "Invalid face count in PLY header",
                        )
                    })?;
                }
            } else if trimmed.starts_with("property float nx") {
                has_normals = true;
            } else if trimmed.starts_with("property uchar red") {
                has_colors = true;
            } else if trimmed.eq("end_header") {
                break;
            }
        }

        Ok(PlyHeaderInfo {
            vertex_count,
            face_count,
            has_normals,
            has_colors,
        })
    }

    /// Read vertices
    fn read_vertices(
        &mut self,
        mesh: &mut Mesh3D,
        header: &PlyHeaderInfo,
    ) -> Result<(), std::io::Error> {
        for _ in 0..header.vertex_count {
            let mut vertex = MeshVertex::default();

            if self.binary {
                // Read binary format
                let mut buffer = [0u8; 4];

                // Read x, y, z
                self.reader.read_exact(&mut buffer)?;
                let x = f32::from_le_bytes(buffer) as f64;

                self.reader.read_exact(&mut buffer)?;
                let y = f32::from_le_bytes(buffer) as f64;

                self.reader.read_exact(&mut buffer)?;
                let z = f32::from_le_bytes(buffer) as f64;

                vertex.point = Point::new(x, y, z);

                // Read normals if available
                if header.has_normals {
                    self.reader.read_exact(&mut buffer)?;
                    let nx = f32::from_le_bytes(buffer) as f64;

                    self.reader.read_exact(&mut buffer)?;
                    let ny = f32::from_le_bytes(buffer) as f64;

                    self.reader.read_exact(&mut buffer)?;
                    let nz = f32::from_le_bytes(buffer) as f64;

                    vertex.normal = Some([nx, ny, nz]);
                }

                // Read colors if available
                if header.has_colors {
                    let mut color_buffer = [0u8; 4];
                    self.reader.read_exact(&mut color_buffer)?;
                    let r = color_buffer[0] as f64 / 255.0;
                    let g = color_buffer[1] as f64 / 255.0;
                    let b = color_buffer[2] as f64 / 255.0;
                    let a = color_buffer[3] as f64 / 255.0;

                    vertex.color = Some([r, g, b, a]);
                }
            } else {
                // Read ASCII format
                let mut line = String::new();
                self.reader.read_line(&mut line)?;
                let parts: Vec<&str> = line.trim().split_whitespace().collect();

                if parts.len() < 3 {
                    return Err(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "Invalid vertex data",
                    ));
                }

                let x = parts[0].parse().map_err(|_| {
                    std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "Invalid vertex x coordinate",
                    )
                })?;

                let y = parts[1].parse().map_err(|_| {
                    std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "Invalid vertex y coordinate",
                    )
                })?;

                let z = parts[2].parse().map_err(|_| {
                    std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "Invalid vertex z coordinate",
                    )
                })?;

                vertex.point = Point::new(x, y, z);

                // Read normals if available
                if header.has_normals && parts.len() >= 6 {
                    let nx = parts[3].parse().map_err(|_| {
                        std::io::Error::new(
                            std::io::ErrorKind::InvalidData,
                            "Invalid vertex normal x component",
                        )
                    })?;

                    let ny = parts[4].parse().map_err(|_| {
                        std::io::Error::new(
                            std::io::ErrorKind::InvalidData,
                            "Invalid vertex normal y component",
                        )
                    })?;

                    let nz = parts[5].parse().map_err(|_| {
                        std::io::Error::new(
                            std::io::ErrorKind::InvalidData,
                            "Invalid vertex normal z component",
                        )
                    })?;

                    vertex.normal = Some([nx, ny, nz]);
                }

                // Read colors if available
                if header.has_colors {
                    let offset = if header.has_normals { 6 } else { 3 };
                    if parts.len() >= offset + 4 {
                        let r: u8 = parts[offset].parse().map_err(|_| {
                            std::io::Error::new(
                                std::io::ErrorKind::InvalidData,
                                "Invalid vertex red color component",
                            )
                        })?;

                        let g: u8 = parts[offset + 1].parse().map_err(|_| {
                            std::io::Error::new(
                                std::io::ErrorKind::InvalidData,
                                "Invalid vertex green color component",
                            )
                        })?;

                        let b: u8 = parts[offset + 2].parse().map_err(|_| {
                            std::io::Error::new(
                                std::io::ErrorKind::InvalidData,
                                "Invalid vertex blue color component",
                            )
                        })?;

                        let a: u8 = parts[offset + 3].parse().map_err(|_| {
                            std::io::Error::new(
                                std::io::ErrorKind::InvalidData,
                                "Invalid vertex alpha color component",
                            )
                        })?;

                        vertex.color = Some([
                            r as f64 / 255.0,
                            g as f64 / 255.0,
                            b as f64 / 255.0,
                            a as f64 / 255.0,
                        ]);
                    }
                }
            }

            mesh.add_vertex(vertex.point);
        }

        Ok(())
    }

    /// Read faces
    fn read_faces(
        &mut self,
        mesh: &mut Mesh3D,
        header: &PlyHeaderInfo,
    ) -> Result<(), std::io::Error> {
        for _ in 0..header.face_count {
            if self.binary {
                // Read binary format
                let mut count_buffer = [0u8; 1];
                self.reader.read_exact(&mut count_buffer)?;
                let count = count_buffer[0] as usize;

                let mut vertices = Vec::with_capacity(count);
                for _ in 0..count {
                    let mut index_buffer = [0u8; 4];
                    self.reader.read_exact(&mut index_buffer)?;
                    let index = i32::from_le_bytes(index_buffer) as usize;
                    vertices.push(index);
                }

                mesh.add_face(vertices);
            } else {
                // Read ASCII format
                let mut line = String::new();
                self.reader.read_line(&mut line)?;
                let parts: Vec<&str> = line.trim().split_whitespace().collect();

                if parts.is_empty() {
                    return Err(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "Invalid face data",
                    ));
                }

                let count = parts[0].parse().map_err(|_| {
                    std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "Invalid face vertex count",
                    )
                })?;

                if parts.len() < count + 1 {
                    return Err(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "Insufficient face vertex indices",
                    ));
                }

                let mut vertices = Vec::with_capacity(count);
                for i in 1..=count {
                    let index = parts[i].parse().map_err(|_| {
                        std::io::Error::new(
                            std::io::ErrorKind::InvalidData,
                            "Invalid face vertex index",
                        )
                    })?;
                    vertices.push(index);
                }

                mesh.add_face(vertices);
            }
        }

        Ok(())
    }
}
